In [1]:


def  calendar_map(date_strings):
    year=date_strings[0:3]
    month = date_string[4:5]
    

In [11]:
"2012-08-05".split('-')[1]

'08'

In [9]:
int(int("2012-08-05"[5:7])/4)

2

In [12]:
# Complete the function below.


def  calendar_map(date_strings):
    ret = []
    
    
    
    
    for i in date_strings:
        haha = i.split('-')
        year=haha[0]
        month = int(int(haha[1])/4+1)
        ret.append(str(year)+'Q'+str(month))
    return ret

In [20]:
calendar_map(["2012-08-05","2012-8-05"])

['2012Q3', '2012Q3']

In [30]:
import math

def divisorGenerator(n):
    large_divisors = []
    for i in range(1, int(math.sqrt(n) + 1)):
        if n % i == 0:
            yield i
            if i*i != n:
                large_divisors.append(n / i)
    for divisor in reversed(large_divisors):
        yield divisor

print (list(divisorGenerator(100)))

[1, 2, 4, 5, 10, 20.0, 25.0, 50.0, 100.0]


In [31]:

def list_divisors(num):
    ''' Creates a list of all divisors of num
    '''
    orig_num = num
    prime_list = list_to_number(int(num / 2) + 1)
    divisors = [1, num]
    for i in prime_list:
        num = orig_num
        while not num % i:
            divisors.append(i)
            num = int(num / i)
    for i in range(len(divisors) - 2):
            for j in range(i + 1, len(divisors) - 1):
                if i and j and j != num and not orig_num % (i * j):
                    divisors.append(i * j)
    divisors = list(set(divisors))
    divisors.sort()
    return divisors

In [32]:
list_divisors(1)

NameError: name 'list_to_number' is not defined

In [46]:
x = 11
i = 1
while i<x:
    if x%i == 0:
        print (i)
    i = i + 1


1


In [77]:
def divisor(x):
    rec = []
    i = 1
    while i<x:
        if x%i == 0:
            rec.append(i)
        i = i + 1
#    if len(rec)==1 and x!=1:
#        rec.append(x)
    if x==1:
        return [1]
    rec.append(x)
    return rec

In [70]:
def sum_div(x):
    return sum(divisor(x))

In [67]:
map([21,11,7],divisor)

TypeError: 'function' object is not iterable

In [80]:
sum_div(7)

8

In [85]:
sum(list(map(sum_div,[1,6,10])))

31

In [86]:
divisor(1)

[1]

In [87]:
divisor(6)

[1, 2, 3, 6]

In [104]:
# Complete the function below.


def divisor(x):
    rec = []
    i = 1
    while i<x:
        if x%i == 0:
            rec.append(i)
        i = i + 1
#    if len(rec)==1 and x!=1:
#        rec.append(x)
    if x==1:
        return [1]
    rec.append(x)
    return rec

def sum_odd_div(x):
    odd_div = []
    for i in divisor(x):
        if i%2!=0:
            odd_div.append(i)
    
    return sum(odd_div)

def  count(numbers):
    return sum(list(map(sum_odd_div,numbers)))


In [105]:
count([1,6,10])

11

In [95]:
sum_odd_div(10)

[1, 5]

In [98]:
list(map(sum_odd_div,[1,6,10]))

[[1], [1, 3], [1, 5]]

In [101]:
sum(list(map(sum(sum_odd_div),[1,6,10])))

TypeError: 'function' object is not iterable

In [107]:
import sys
import os

if __name__ == "__main__":
    f = open(os.environ['OUTPUT_PATH'], 'w')

    zombies_cnt = 0
    zombies_cnt = int(input())
    zombies_i = 0
    zombies = []
    while zombies_i < zombies_cnt:
        try:
            zombies_item = str(input())
        except:
            zombies_item = None
        zombies.append(zombies_item)
        zombies_i += 1


    res = zombieCluster(zombies);
    f.write(str(res) + "\n")


    f.close()

KeyError: 'OUTPUT_PATH'

In [137]:
a=np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])

In [112]:
a

array([[1, 1, 0, 0],
       [1, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 1]])

In [114]:
a[:][1]

array([1, 1, 1, 0])

In [115]:
a[0]

array([1, 1, 0, 0])

In [109]:
import numpy as np

In [129]:
def is_sigle(a,i):
    if sum(a[i])==sum(a[:][i])==1:
        return True
    else:
        return False
    

In [130]:
is_sigle(a,3)

True

In [125]:
sum(a[3])

1

In [126]:
sum(a[:][3])

1

In [135]:
# Complete the function below.

def is_sigle(a,i):
    if sum(a[i])==sum(a[:][i])==1:
        return True
    else:
        return False
    

    
def zombieCluster(zombies):
    aa = np.array(zombies)
    dim = len(aa)
    clust = 1
    flag = 0
    for j in range(dim):
        if is_sigle(aa,j)==True:
            if flag==1:
                clust+1
                flag = 0
            clust+=1
            continue
        
        else:
            flag = 1
    return clust



In [138]:
zombieCluster(a)a

5

In [141]:
for i in range(1,4):
    print(i)

1
2
3


In [155]:


def single(n):
    buffer= []
    if n ==0:
        return 0
    elif n==2:
        return 2
    elif n==1:
        return 1
    elif n==3:
        return 4
    for i in range(1,4):
        buffer.append(single(n-i))
    return sum(buffer)

In [183]:
single(16)

10609

In [167]:
s = int(input().strip())
n=[]
for a0 in range(s):
    n.append( int(input().strip()))





3
1
3
7


In [162]:
a0

2

In [163]:
s

3

In [164]:
n

7

In [168]:
n

[1, 3, 7]

In [185]:
single(200)

KeyboardInterrupt: 